### PR TITLE
[network v2]: Add support for network segments update and import

### LINKED ISSUE #1477: Missing configurations after importing openstack networks
Hi,

we want to import manually created networks into Terraform, but we noticed that not all configurations are imported. If I import provider networks, i.e. external ones, then the configurations `network_type`, `physical_network` and `segmentation_id` are missing in the Terraform State, although they can be seen with `openstack network show xyz`.

Since these configurations are not included in the terraform state, programming these configurations via terraform and then apply leads to a forced recreation of the network - undesirable.

If you comment out the configuration (see Terraform Configuration Files) Terraform says: 
```
No changes. Your infrastructure matches the configuration.
```

### Terraform Version
```
Terraform v1.3.7
on linux_amd64
```

### Affected Resource(s)
- all `openstack_networking_network_v2.`


### Terraform Configuration Files
```hcl
/*
terraform import -var-file secret.tfvars openstack_networking_network_v2.network id
*/

resource "openstack_networking_network_v2" "network" {
  name           = "network"
  admin_state_up = true
  shared         = false
  external       = true
  tenant_id      = data.openstack_identity_project_v3.project.id
  segments {
      physical_network = "provider"
      segmentation_id  = "123"
      network_type     = "vlan"
   }
}
```

### Expected Behavior
When importing a network, all configurations should be imported so that you can manage all configurations via Terraform afterwards.

### Actual Behavior

Terraform wants to recreate the Network.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

###  LOGS

```
2023-02-09T12:47:37.136+0100 [INFO]  provider.terraform-provider-openstack_v1.49.0: 2023/02/09 12:47:37 [DEBUG] OpenStack Response Headers:                                                                                          
Content-Length: 689                                                                                                                                                                                                                  
Content-Type: application/json                                                                                                                                                                                                       
Date: Thu, 09 Feb 2023 11:47:37 GMT                                                                                                                                                                                                  
X-Openstack-Request-Id: req-f5e978d5-2715-4b51-9d21-e6caa9ce4414: timestamp=2023-02-09T12:47:37.136+0100                                                                                                                             
2023-02-09T12:47:37.136+0100 [INFO]  provider.terraform-provider-openstack_v1.49.0: 2023/02/09 12:47:37 [DEBUG] OpenStack Response Body: {                                                                                           
  "network": {                                                                                                                                                                                                                       
    "admin_state_up": true,                                                                                                                                                                                                          
    "availability_zone_hints": [],                                                                                                                                                                                                   
    "availability_zones": [                                                                                                                                                                                                          
      "nova"                                                                                                                                                                                                                         
    ],                                                                                                                                                                                                                               
    "created_at": "2021-03-18T15:11:04Z",                                                                                                                                                                                            
    "description": "",                                                                                                                                                                                                               
    "id": "$ID",                                                                                                                                                                                    
    "ipv4_address_scope": null,                                                                                                                                                                                                      
    "ipv6_address_scope": null,                                                                                                                                                                                                      
    "is_default": false,                                                                                                                                                                                                             
    "mtu": 1500,                                                                                                                                                                                                                     
    "name": "$NAME",                                                                                                                                                                                                             
    "port_security_enabled": true,                                                                                                                                                                                                   
    "project_id": "$PROJECT",                                                                                                                                                                                
    "provider:network_type": "vlan",                                                                                                                                                                                                 
    "provider:physical_network": "provider",                                                                                                                                                                                         
    "provider:segmentation_id": $VLAN,                                                                                                                                                                                                  
    "revision_number": 2,                                                                                                                                                                                                            
    "router:external": true,                                                                                                                                                                                                         
    "shared": false,                                                                                                                                                                                                                 
    "status": "ACTIVE",                                                                                                                                                                                                              
    "subnets": [                                                                                                                                                                                                                     
      "$SUBNETS"                                                                                                                                                                                         
    ],                                                                                                                                                                                                                               
    "tags": [],                                                                                                                                                                                                                      
    "tenant_id": "$TENANT",                                                                                                                                                                                 
    "updated_at": "2021-03-18T15:15:28Z"                                                                                                                                                                                             
  }                                                                                                                                                                                                                                  
}: timestamp=2023-02-09T12:47:37.136+0100

### PR DESCRIPTION
**Pull request by kayrus**
Fixes #1477

### CODE REVIEW

File: openstack/data_source_openstack_networking_network_v2.go [hunk 1]
```diff
@@ -239,6 +260,7 @@ func dataSourceNetworkingNetworkV2Read(ctx context.Context, d *schema.ResourceDa
 	d.Set("shared", strconv.FormatBool(network.Shared))
 	d.Set("external", network.External)
 	d.Set("tenant_id", network.TenantID)
+	d.Set("segments", flattenNetworkingNetworkSegmentsV2(network))
```
Comment (nikParasyr) [inline openstack/data_source_openstack_networking_network_v2.go:263]: Can you update docs to mention that segments are exported as well?

File: openstack/resource_openstack_networking_network_v2.go [hunk 2]
```diff
@@ -88,23 +88,20 @@ func resourceNetworkingNetworkV2() *schema.Resource {
...
 						},
 						"network_type": {
 							Type:     schema.TypeString,
 							Optional: true,
-							ForceNew: true,
 						},
 						"segmentation_id": {
 							Type:     schema.TypeInt,
 							Optional: true,
-							ForceNew: true,
```
Comment (nikParasyr) [inline openstack/resource_openstack_networking_network_v2.go:107]: Based on [docs](https://docs.openstack.org/api-ref/network/v2/index.html?expanded=update-network-detail#networks), this can only be updated if network_type == vlan. Can you update docs to mention this?

**Review by nikParasyr — CHANGES_REQUESTED** [review]
@kayrus Just some doc updates. Other than that LGTM

File: openstack/resource_openstack_networking_network_v2.go (hunk 2 above)
Comment (kayrus) [reply openstack/resource_openstack_networking_network_v2.go:107]: You'r not quire right. It depends on the ml2 plugin. I added this info.

File: openstack/data_source_openstack_networking_network_v2.go (hunk 1 above)
Comment (kayrus) [reply openstack/data_source_openstack_networking_network_v2.go:263]: done

**Review by nikParasyr — APPROVED** [review]
