### PR TITLE
Fix skipping not overridden labels uisng '--merge-labels'

### LINKED ISSUE #1327: Terraform apply recreates openstack_containerinfra_cluster_v1 every time I apply even though there are no changes in code
### Terraform Version
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.43.1

### Affected Resource(s)
- openstack_containerinfra_cluster_v1

### Terraform Configuration Files
```json
 "KubernetesClusterPrivate": {
        "cluster_template_id": "bd998c9d-cc22-4701-9c6d-ac90bf2db8cf",
        "fixed_network": "${openstack_networking_network_v2.PublicNetworkKubernetes.name}",
        "fixed_subnet": "${openstack_networking_subnet_v2.PublicNetworkKubernetesSubnet.name}",
        "flavor": "m1.large",
        "floating_ip_enabled": false,
        "keypair": "dniasoff-desktop",
        "labels": {
          "auto_scaling_enabled": "True",
          "auto_healing_enabled": "True",
          "kube_dashboard_enabled": "True",
          "influx_grafana_dashboard_enabled": "True",
          "min_node_count": "1",
          "max_node_count": "5",
          "ingress_controller": "octavia"
        },
        "master_count": 1,
        "master_flavor": "m1.medium",
        "merge_labels": true,
        "name": "DevToolStackProdKubernetesClusterPrivate",
        "node_count": 1,
        "depends_on": [],
        "//": {
          "metadata": {
            "path": "DevToolStackProd/KubernetesClusterPrivate",
            "uniqueId": "KubernetesClusterPrivate"
          }
        }
      }
```

### Debug Output
https://gist.github.com/dniasoff/04593214345e2edf4c9332a2986c28b6

### Expected Behavior
No changes should have been detected

### Actual Behavior
A terraform apply will recreate the existing cluster every time I apply even if there are no changes to the code.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Running version v0.43.1 as 0.45.0 crashes with bug described in Github issue below

### References
- https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1308

### PR DESCRIPTION
**Pull request by pawcykca**
Close #1327

This PR should fix issue when TF try to recreate the existing cluster every time even if there are no changes to the code using '--merge-labels option.

### CODE REVIEW

**Comment by MrFreezeex** [comment]
I think the code make sense, but are you trying to fix the case where a cluster that is being imported in Terraform right? Because if that's the case it would still want to recreate the cluster after that. The issue being that merge_labels can't be read in the magnum API: it's not in gophercloud and the actual json returned by magnum seems to always return false (at least in my env). So basically on import, the state of merge_labels would always be false and if you have set to true in your code it would want to replace it...

Possible way to fix it would be to try to make magnum fixing that + having it in gophercloud and actually read it in terraform or finding a trick to determine if merge_labels is supposed to be true in terraform read function...

File: openstack/resource_openstack_containerinfra_cluster_v1.go [hunk 1]
```diff
@@ -355,7 +355,11 @@ func resourceContainerInfraClusterV1Read(_ context.Context, d *schema.ResourceDa
 
 	labels := s.Labels
 	if d.Get("merge_labels").(bool) {
-		labels = containerInfraV1GetLabelsMerged(s.LabelsAdded, s.LabelsSkipped, s.LabelsOverridden, s.Labels)
+		resourceDataLabels, err := expandContainerInfraV1LabelsMap(d.Get("labels").(map[string]interface{}))
+		if err != nil {
+			return diag.FromErr(err)
+		}
+		labels = containerInfraV1GetLabelsMerged(s.LabelsAdded, s.LabelsSkipped, s.LabelsOverridden, s.Labels, resourceDataLabels)
```
Comment (MrFreezeex) [inline openstack/resource_openstack_containerinfra_cluster_v1.go:362]: Also in what case you would need to get the labels from the state? It seems to me that with this change if you would want to delete a label it would not consider that the cluster changed.

But since I am not sure what you are trying to fix exactly so perhaps I missed something.

Comment (pawcykca) [reply openstack/resource_openstack_containerinfra_cluster_v1.go:362]: This code fixes issue described in #1327.

Currently when you create cluster and nodegroup using 'merge_label option' with labels that looks like below:
```
$ cat cluster.tf 
resource "openstack_containerinfra_cluster_v1" "cluster_1" {
  ...
  merge_labels        = true
  labels = {
    # unchanged (the same as in the cluster template)
    availability_zone = "zone1"
    # overridden
    boot_volume_size = 15
    # added
    boot_volume_type = "gp-ssd"
  }

$ cat nodegroup.tf 
resource "openstack_containerinfra_nodegroup_v1" "nodegroup" {
  ...
  merge_labels        = true
  labels = {
    # unchanged (the same as in the cluster template)
    availability_zone = "zone1"
    # overridden
    boot_volume_size = 20
    # added
    docker_volume_type = "gp-hdd"
  }
```
and perform again `apply` operation (without any changes in .tf files) then TF will try to recreate both cluster and nodegroup again
```
Terraform will perform the following actions:

  # openstack_containerinfra_cluster_v1.cluster_1 must be replaced
-/+ resource "openstack_containerinfra_cluster_v1" "cluster_1" {
	  ...
      ~ labels              = { # forces replacement
          + "availability_zone" = "zone1"
            # (2 unchanged elements hidden)
        }
      ...
        # (7 unchanged attributes hidden)
    }

  # openstack_containerinfra_nodegroup_v1.nodegroup must be replaced
-/+ resource "openstack_containerinfra_nodegroup_v1" "nodegroup" {
	  ...
      ~ labels             = { # forces replacement
          + "availability_zone"  = "zone1"
            # (2 unchanged elements hidden)
        }
      ...
        # (6 unchanged attributes hidden)
    }

Plan: 2 to add, 0 to change, 2 to destroy.
```
This is because defined labels that are the same as in the cluster template are not stored in cluster/nodegroup object by Openstack API.

Comment (MrFreezeex) [reply openstack/resource_openstack_containerinfra_cluster_v1.go:362]: Weird I would expect to find those labels in labels skipped or even override somehow... But by reading the state of terrwform I don't think that you are able to remove an existing labels anymore... Could you test this case? If it's indeed not returned anywhere in the Openstack cluster API, it would probably require fetching the labels from the cluster template unfortunately...

Comment (pawcykca) [reply openstack/resource_openstack_containerinfra_cluster_v1.go:362]: > Weird I would expect to find those labels in labels skipped or even overridden somehow...

This is mapped as below
```
  merge_labels        = true
  labels = {
    # unchanged (the same as in the cluster template) -> not stored in any field on Magnum API
    availability_zone = "zone1"
    # overridden -> stored in 'labels_overridden'
    boot_volume_size = 15
    # added -> stored in 'labels_added'
    boot_volume_type = "gp-fast"
  }
```

> But by reading the state of terrwform I don't think that you are able to remove an existing labels anymore... Could you test this scenario?

Works fine for each type of below labels
```
  merge_labels        = true
  labels = {
    # unchanged (the same as in the cluster template)
    # availability_zone = "zone1"
    # overridden
    #boot_volume_size = 15
    # added
    #boot_volume_type = "gp-fast"
  }
```
```
Terraform will perform the following actions:

  # openstack_containerinfra_nodegroup_v1.nodegroup must be replaced
-/+ resource "openstack_containerinfra_nodegroup_v1" "nodegroup" {
     ...
      ~ labels             = {
          - "availability_zone"  = "zone1"
          - "boot_volume_size"   = "20"
          - "docker_volume_type" = "gp-fast"
        } -> (known after apply) # forces replacement
     ...
        # (7 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

Comment (MrFreezeex) [reply openstack/resource_openstack_containerinfra_cluster_v1.go:362]: Oh ok I see then it should work indeed! Thanks :).

**Review by MrFreezeex — APPROVED** [review]

**Comment by nikParasyr** [comment]
@ozerovandrei Can you have a look into this as well?
From my side  this looks ok, but i dont have any environment to actually test it

**Review by ozerovandrei — APPROVED** [review]
I also don't have a Magnum environment currently but LGTM
